name: SpigotTutorial
version: '${project.version}'
main: me.dollarmc.spigottutorial.SpigotTutorial
api-version: '1.20'
authors: [Cash]
description: Spigot plugin development practice
commands:
  die:
    description: An easy way out.
    aliases: [kys]
    usage: /<command>
  god:
    description: Become invincible.
    usage: /<command>
  feed:
    description: Feeds player.
    usage: /<command>